version: 1.0.0+dev

name: collabree
description: This is Collabree
homepage: https://www.collabree.com/

publish_to: "none"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  built_collection: ^4.3.2
  charts_flutter: ^0.9.0
  easy_rich_text: ^0.5.0
  equatable: ^1.2.3
  flutter_bloc: ^6.0.1
  flutter_icons: ^1.1.0
  http: ^0.12.2
  intl: ^0.16.0
  logger: ^0.9.2
  provider: ^4.3.2+1
  quiver: ^2.0.5
  rxdart: ^0.24.1
  time_machine: ^0.9.13
  uuid: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^7.0.2
  intl_translation: ^0.17.10
  pedantic: ^1.9.0
  test: ^1.15.2

flutter:
  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
